Models/Developer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Developer.Models
{
    public class Developers
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]

        public int Age { get; set; }

        [Required]

        public string Job { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Developer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DeveloperController.cs
using Developer.Data;
using Developer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Developer.Controllers
{
    public class DeveloperController : Controller
    {
        public readonly ApplicationDbContext _context;


        public DeveloperController(ApplicationDbContext context)
        {
            _context = context;

        }
        public IActionResult Index()
        {
            return View();
        }
       
        [HttpGet]
        public JsonResult GetAlldevelopers()
        {
            var devList = _context.Developers.ToList().OrderBy(x => x.Id);
            return Json(new { data = devList });
        }

        [HttpPost]
        public ActionResult savedeveloper(List<Developers> Developerlist)
        {
            using (var dbContextTransaction = _context.Database.BeginTransaction())
            {
                try
                {
                    foreach(var dev in Developerlist)
                    {
                        Developers oldobjWithName = _context.Developers.Where(x => x.Name.ToLower() == dev.Name ).FirstOrDefault();
                        bool alreadyExist = false;
                        if (oldobjWithName != null)
                        {
                            alreadyExist = true;
                        }
                        if (alreadyExist)
                        {
                            return Json(new { alreadyExist });
                        }
                        _context.Add(dev);
                        _context.SaveChanges();
                    }
                    dbContextTransaction.Commit();
                }
                catch (Exception ex)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { status = false });

                }
            }
                return Json(new { status  = true });
            
        }
         
        public ActionResult DeleteDeveloper(int Id)
        {
            try
            {
                var developer = _context.Developers.Find(Id);
                _context.Developers.Remove(developer);
                _context.SaveChanges();
                return Json(new { status = true });
            }
            catch (Exception ex)
            {
                return Json(new { status = false });
            }
        }  

        public IActionResult EditDeveloper(int id)
        {
            var developer = _context.Developers.Find(id);
            return new JsonResult(developer);
        }

        [HttpPost]
        public ActionResult UpdateDeveloper(Developers obj)
        {
            using (var dbContextTransaction = _context.Database.BeginTransaction())
            {
                try
                {
                    Developers oldobjWithName = _context.Developers.Where(x => x.Name.ToLower() == obj.Name && x.Id !=obj.Id).FirstOrDefault();
                    bool alreadyExist = false;
                    if (oldobjWithName != null)
                    {
                        alreadyExist = true;
                    }
                    if (alreadyExist)
                    {
                        return Json(new { alreadyExist });

                    }

                    _context.Update(obj);
                    _context.SaveChanges();
                    dbContextTransaction.Commit();
                }
                catch (Exception ex)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { status = false });

                }
            }
            return Json(new { status = true });
        }
    }
}

Controllers/HomeController.cs
using Developer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Developer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Developer/Index.cshtml
@{
    ViewData["Title"] = "Developers";
}

@section Scripts
    {
    <script src="~/js/Developer.js"></script>
   

}
<div class="text-center">
    <h1 class="display-4">Developers</h1>
</div>


<p>
    <button type="button" class="btn btn-primary" onclick="CreateNewModal()">Create New</button>
</p>


<div class="col-12 border bg-light" style="border-radius:20px; padding:30px;">
    <table id="developerListTable" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>

                <th>#</th>
                <th>Name</th>
                <th>Age</th>
                <th>Job Title</th>
                <th></th>
                <th></th>


            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div class="modal" tabindex="-1" role="dialog" aria-labelledby="AddDevModal" aria-hidden="true" id="AddDevModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create New Developer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="clearmodal()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="DeveloperDivParent">
                <div class="row mb-3 child_sub_container" style="margin-top:-16px" id="duplicater">
                    <div class="col-4">
                        <div class="form-group child_sub"><p>Name:</p><input type="text" class="form-control " id="txt_Name" required /></div>
                        <div class="form-group child_sub"><input type="hidden" class="form-control" id="txt_Id" /></div>
                    </div>
                    <div class="col-4">
                        <div class="form-group child_sub"><p>Age:</p><input type="text" class="form-control" id="txt_Age" required /></div>
                    </div>
                    <div class="col-4">
                        <div class="form-group child_sub"><p>Job Title:</p><input type="text" class="form-control" id="txt_JobTitle" required /></div>
                    </div>

                    <hr />
                </div>

            </div>
            <div class="modal-footer">
                <button id="createmorebutton" class="btn btn-primary" onclick="CreationNewDiv()">Add More</button>
                <button type="submit" id="savebutton" class="btn btn-primary" onclick="save()">Save</button>
                <button type="submit" id="editbutton" class="btn btn-primary d-none" onclick="update()">Edit</button>
                
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="clearmodal()">Close</button>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Developer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Developer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Developer" asp-action="Index">Developer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Developer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>